### PR TITLE
Create cs.json

### PR DESCRIPTION
**Pull request by michaelkmoch**
Hi, I created a translation for czech language 👍🏻

### CODE REVIEW

**Comment by ekutner** [comment]
Thank you, but please take the base translation file from the *config_flow* branch, which added some other translation strings and is the basis for version 1.0.0

**Comment by ekutner** [comment]
you're still not using the correct base branch, you can either rebase or merge the config_flow branch and use one of the translation files from there as the base for your translation.

**Comment by michaelkmoch** [comment]
> you're still not using the correct base branch, you can either rebase or merge the config_flow branch and use one of the translation files from there as the base for your translation.

Well, I used latest en.json and both files seem to me be same 😅
Sorry for troubles, I am new to GitHub.

**Comment by ekutner** [comment]
Thanks, I've merged it manually

**Review by ekutner — APPROVED** [review]

**Pull request closed without merging**
