### PR TITLE
just some translations and 2 new programs

### PR DESCRIPTION
**Pull request by d0np3p3**
"LaundryCare.Dryer.Program.ColdRefresh.1Piece": "Trocknen: 1 Hemd Auffrischen",
      "LaundryCare.Dryer.Program.ColdRefresh.5Piece": 5 "Trocknen: 5 HemdenAuffrischen",

 synced sensors.de.json with  select.de.json

Next Step 2 get missing lines from sensors.en

### CODE REVIEW

**Comment by ekutner** [comment]
The English translation is the canonical version which should have the most complete set of translate ENUM values. Can you please confirm that all of these values exist in the English translation files and you just added them to the German version where they were missing?

**Comment by d0np3p3** [comment]
I will update the Englisch parts too, but sensors.en.json and select.en.json are different. 
Should they be synced?

**Comment by ekutner** [comment]
The sensors translation file is a superset of the select file. In theory they can be merged but it's not necessary.

**Comment by ekutner** [comment]
Thanks

**Pull request merged**
